name: Conan2 Build C/C++ dummy project

on:
  push:
    branches:
      - "master"
      - "task/**"
  pull_request:
    branches:
      - "master"
      - "task/**"

  workflow_dispatch:

jobs:
  conan_build_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check Python & pip
        run: |
          python3 --version
          pip3 --version

      - name: Install Conan
        run: |
          python3 -m pip install "conan==2.24.0"
          echo "**********"
          echo "Installed conan version:"
          conan --version
          echo "**********"

      - name: Conan config install
        run: |
          conan config install conan2_config

      - name: Conan Build
        run: |
          conan build packages/conan2_dummy -pr:b=Linux-gcc-11 -pr:h=Linux-gcc-11
